modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Villager%20Names"
logoFile="icon.png"

[[mods]]
modId="villagernames"
version="7.1"
displayName="Villager Names"
displayURL="https://curseforge.com/minecraft/mc-mods/villager-names"
authors="Rick South"
description='''Gives all villagers and villager-like entities their own name.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.villagernames]]
    modId="collective"
    mandatory=true
    versionRange="[7.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagernames]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"